### ISSUE TITLE
No file and folder found error.

### ISSUE THREAD

**Issue by ahmadawais** [devbridge/Styleguide#117]
On my very first run this is what I got.

```bash
[13:59:15] Using gulpfile ~/Documents/Websites/wtwp.dev/wp-content/themes/writeable/gulpfile.js
[13:59:15] Starting 'start-styleguide'...
[13:59:15] 'start-styleguide' errored after 318 μs
[13:59:15] Error: ENOENT: no such file or directory, open './styleguide/config.txt'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.exports.startServer (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/devbridge-styleguide/index.js:14:30)
  at Gulp.<anonymous> (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/gulpfile.js:111:14)
  at module.exports (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at nextTickCallbackWith0Args (node.js:419:9)
  at process._tickCallback (node.js:348:13)
  at Function.Module.runMain (module.js:444:11)
  at startup (node.js:136:18)
  at node.js:966:3
```

**Comment by ahmadawais** [comment]
I created the folder and file myself only to get this error

```bash
[14:01:19] 'start-styleguide' errored after 422 μs
[14:01:19] SyntaxError: Unexpected end of input
  at Object.parse (native)
  at Object.exports.startServer (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/devbridge-styleguide/index.js:14:21)
  at Gulp.<anonymous> (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/gulpfile.js:111:14)
  at module.exports (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at nextTickCallbackWith0Args (node.js:419:9)
  at process._tickCallback (node.js:348:13)
  at Function.Module.runMain (module.js:444:11)
  at startup (node.js:136:18)
  at node.js:966:3
```

**Comment by miezis** [comment]
Why did you have to create them yourself? They were not created during styleguide initialize? My guess now is that your config is not correct now.

**Comment by gediminas-s** [comment]
Could you give us more details about your run:
- did you successfully initialized styleguide?
- is your styleguide folder placed in your project's root dir?
- what files did you copied your self?

**Comment by ivayloc** [comment]
```
Error: Not Found
    at c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\app.js:36:13
    at Layer.handle [as handle_request] (c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:302:13)
    at c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:321:12)
    at next (c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:261:10)    
    at c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\app.js:27:3
    at Layer.handle [as handle_request] (c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:302:13)
    at c:\Users\icherkezov\Documents\_lab\css-doc\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:270:7
```

Hi, I am experiencing the same error, what I have done so far is to:
- install styleguide through npm
- initialize styleguide 
- run the gulp task

**Comment by piotr-gawlowski** [comment]
I have exactly same issue, steps:
`sudo npm install devbridge-styleguide -g`
`styleguide initialize`
`gulp start-styleguide`

**Comment by miezis** [comment]
@ivayloc @piotr-gawlowski  These errors are not related with what @ahmadawais described. Your described errors are mentioned in #109 and it's not an issue with styleguide itself, but documentation of how to use it. It's improved as we speek. For now please follow this:

My guess is that you are trying to reach your styleguide through hostname that exposes only styleguide API.

As it was mentioned - your styleguide static files should be served by your project server, as we can see from readme:

You should access your styleguide going to http://your-project-hostname/styleguide/index.html

So you can view your styleguide anytime, but enable editing only locally running gulp start-styleguide.

**Comment by ahmadawais** [comment]
@miezis  I had missed the following step.

```bash
styleguide initialize
```

Now when I initialized the styleguide, after that I ran into different errors.

```bash
Styleguide server listening on port 8080
Error: Not Found
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/devbridge-styleguide/app.js:36:13
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/devbridge-styleguide/app.js:27:3
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at urlencodedParser (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/body-parser/lib/types/urlencoded.js:84:40)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at jsonParser (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/body-parser/lib/types/json.js:96:40)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at expressInit (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/middleware/init.js:23:5)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at query (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/middleware/query.js:28:5)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at Function.proto.handle (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:166:3)
  at EventEmitter.app.handle (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/application.js:170:10)
  at Server.app (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/express.js:28:9)
  at emitTwo (events.js:87:13)
  at Server.emit (events.js:172:7)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

Error: Not Found
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/devbridge-styleguide/app.js:36:13
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/devbridge-styleguide/app.js:27:3
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at urlencodedParser (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/body-parser/lib/types/urlencoded.js:84:40)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at jsonParser (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/body-parser/lib/types/json.js:96:40)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at expressInit (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/middleware/init.js:23:5)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at query (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/middleware/query.js:28:5)
  at Layer.handle [as handle_request] (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:302:13)
  at /Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:261:10)
  at Function.proto.handle (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/router/index.js:166:3)
  at EventEmitter.app.handle (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/application.js:170:10)
  at Server.app (/Users/ahmadawais/Documents/Websites/wtwp.dev/wp-content/themes/writeable/node_modules/express/lib/express.js:28:9)
  at emitTwo (events.js:87:13)
  at Server.emit (events.js:172:7)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

![](https://i.imgur.com/WblkEmW.jpg)

**Comment by miezis** [comment]
@ahmadawais You've set up your styleguide correctly now and it should be working, just to clarify, taken from #109 :

You are trying to reach your styleguide through hostname that exposes only styleguide API.

As it was mentioned - your styleguide static files should be served by your project server, as we can see from readme:

You should access your styleguide going to http://your-project-hostname/styleguide/index.html

So you can view your styleguide anytime, but enable editing only locally running gulp start-styleguide.

We're working on improving the documentation about setup, because a lot of users ran into this problem.

**Comment by ahmadawais** [comment]
@miezis If I go to the file and open it manually the `index.html file I meant. There is nothing inside it. As shown in the image above. If I try to access it via ` http://wtwp.dev/styleguide/index.html` on a local WP theme project, it leads to `404` error. :(

**Comment by miezis** [comment]
@ahmadawais You should expose styleguide folder as static resource with the server you're runing your project on.

**Comment by danieldafoe** [comment]
Hey @ahmadawais . I was having the exact same issues as you. It's true that the documentation is extremely ambiguous, but I found that if I ran another local server and navigated to the `/styleguide/index.html` that was generated, I do see what's expected:

<img width="1440" alt="screen shot 2016-04-25 at 11 44 46 am" src="https://cloud.githubusercontent.com/assets/6425338/14789575/318d6310-0adb-11e6-929d-1242f3f21655.png">

Hopefully this helps you out!

**Comment by ottz0** [comment]
Same error here following instructions

Error: Not Found
   at /home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/app.js:36:13
   at Layer.handle [as handle_request] (/home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:302:13)
   at /home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:321:12)
   at next (/home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:261:10)
   at /home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/app.js:27:3
   at Layer.handle [as handle_request] (/home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:302:13)
   at /home/ottz/sandbox/temp-builds/test_styleguide/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:270:7

**Comment by miezis** [comment]
@ottz0 As mentioned before couple of times you need a server to expose static styleguide files, for example your project (for which you're making the styleguide) server.

**Comment by ottz0** [comment]
Why isn't written into the gulpfile then if its a requirement?

**Comment by miezis** [comment]
Gulpfile? It's written in readme, it's quite ambiguous now, but will be improved with the landing page of this tool.

**Comment by ericholmer** [comment]
@miezis I may be having similar issues? 

Running live-server as recommended in the instructions and also running the style guide, however when I go to scrape the variables I get the following error. 

I have my config.txt setup to read: 
  "sassVariables": "styleguide/scss/file.scss",

Any thoughts? 

```
Error: ENOENT: no such file or directory, open 's'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.exports.scrapeTheme (/Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/routes/sassScraper.js:224:13)
    at /Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/routes/scrape.js:127:29
    at Layer.handle [as handle_request] (/Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at /Users/ericholmer/Sites/style guide test/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:267:22
```

**Comment by miezis** [comment]
Wrong configuration, should be "sassVariables": ["styleguide/scss/file.scss"]

**Comment by ericholmer** [comment]
@miezis Many thanks.

**Comment by ahmadawais** [comment]
@miezis Can you elaborate on "you need a server to expose static styleguide files" I am using DesktopServer to build WP theme on a local Mac. It also has hostnames like domain.dev. What do I need to do to expose the static files since going to that link leads to a WP 404.

**Comment by nynban** [comment]
@danieldafoe I dont see the button "New Snippet" on my Styleguide.  Please help.
