### ISSUE TITLE
All markers required in Sass files

### ISSUE THREAD

**Issue by sebald** [devbridge/Styleguide#130]
This is the relevant part of my `config.txt` (btw, why isn't it `.json`?):

```
"sassVariables": [
  "src/styles/core/color.scss",
  "src/styles/core/font.scss"
]
```

Both files need to have the smart quotes, otherwhise this gets thrown:

```
Color markers not found in src/styles/core/font.scss.
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at compareForReport (<path to project>/node_modules/devbridge-styleguide/routes/sassScraper.js:210:33)
    at Object.exports.scrapeTheme (<path to project>/node_modules/devbridge-styleguide/routes/sassScraper.js:245:3)
    at <path to project>/node_modules/devbridge-styleguide/routes/scrape.js:127:29
    at Layer.handle [as handle_request] (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at next (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at <path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:321:12)
    at next (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:166:3)
    at router (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:35:12)
    at Layer.handle [as handle_request] (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:302:13)
    at <path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:321:12)
    at next (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:261:10)
    at <path to project>/node_modules/devbridge-styleguide/app.js:27:3
    at Layer.handle [as handle_request] (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (<path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:302:13)
    at <path to project>/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:270:7
```

Would be nice if this isn't necessary 😄 

## Quick fix 
Just add empty smart comments. E.g. in the `font.scss`:

```sass
//-- typo:start --//
$Font-roboto: 'Roboto', sans-serif; // 300, 300 italic, 400, 400 italic, 700, 700 italic
//-- typo:end --//
//-- colors:start --//
//-- colors:end --//
```

**Comment by miezis** [comment]
This issue is know and mentioned in #124 . It'll be fixed. The extension is txt, because not all servers lets to serve json as static resource by default.

**Comment by sebald** [comment]
Thanks for the info, sorry for the duplicate.
