### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by heymynameisrob** [devbridge/Styleguide#146]
Hey,
I've installed the npm package fine and added the task to my gulp file. But I seem to get an error and it aborts.

I'm not using a localhost server. I'm using a remote server thats through my LAN.

Any help?

**Comment by VaclovasV** [comment]
@heymynameisrob - can you add some more details, about what errors are you having?

**Comment by heymynameisrob** [comment]
I try to run gulp start-styleguide and I get this error:

> Starting 'start-styleguide'...
> [14:41:40] 'start-styleguide' errored after 2.46 ms
> [14:41:40] SyntaxError: Unexpected token ,
>     at Object.parse (native)
>     at Object.exports.startServer (/Volumes/web/WeLaunch/wp-content/themes/WeLaunch2016/node_modules/devbridge-styleguide/index.js:16:20)
>     at Gulp.<anonymous> (/Volumes/web/WeLaunch/wp-content/themes/WeLaunch2016/gulpfile.js:78:14)
>     at module.exports (/Volumes/web/WeLaunch/wp-content/themes/WeLaunch2016/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/Volumes/web/WeLaunch/wp-content/themes/WeLaunch2016/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/Volumes/web/WeLaunch/wp-content/themes/WeLaunch2016/node_modules/orchestrator/index.js:214:10)
>     at Gulp.Orchestrator.start (/Volumes/web/WeLaunch/wp-content/themes/WeLaunch2016/node_modules/orchestrator/index.js:134:8)
>     at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
>     at doNTCallback0 (node.js:419:9)
>     at process._tickCallback (node.js:348:13)

**Comment by VaclovasV** [comment]
@heymynameisrob could you try to update your global gulp?

**Comment by gediminas-s** [comment]
@heymynameisrob did you manage to run styleguide?
