### ISSUE TITLE
Gulp task help

### ISSUE THREAD

**Issue by brandalist** [devbridge/Styleguide#147]
Why is my gulp file doing this? Why is it not defined?

ReferenceError: gulp is not defined
    at Object.<anonymous> (/Users/rsegarra/styleguide/gulpfile.js:3:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:150:63)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:193:16)
5012-C02MLFH0FD57:styleguide rsegarra$

**Comment by VaclovasV** [comment]
@brandalist maybe tyou are missing global gulp install?

**Comment by GodwinSamuel** [comment]
Seems like you didn't initialize gulp

```
// Initializing Gulp
var gulp = require('gulp');

// Running Gulp Task
var styleguide = require('devbridge-styleguide');

gulp.task('start-styleguide', function () {
  styleguide.startServer();
});


// Default Task
gulp.task('default', ['scripts']);
```

Paste the above code in gulpfile.js that would help :)
