### ISSUE TITLE
Issue using styleguide start

### ISSUE THREAD

**Issue by anthonycluse** [devbridge/Styleguide#165]
I get an issue using styleguide start.

    Styleguide server listening on port 8889
    Error: Not Found
        at C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\app.js:36:13
        at Layer.handle [as handle_request] (C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\layer.js:82:5)
        at trim_prefix (C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:302:13)
        at C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:270:7
        at Function.proto.process_params (C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:321:12)
        at next (C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:261:10)
        at C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\app.js:27:3
        at Layer.handle [as handle_request] (C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\layer.js:82:5)
        at trim_prefix (C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:302:13)
        at C:\Users\can\AppData\Roaming\npm\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:270:7

**Comment by nynban** [comment]
i have the same problem.  Is there an answer for this?

**Comment by VaclovasV** [comment]
@anthonycluse  @nynban  - could you provide your operating system?

**Comment by nynban** [comment]
@VaclovasV  i am running on OS X EI Capitan.  It works now but the edit function doesnt show

**Comment by miezis** [comment]
When did this error occur?

**Comment by shelune** [comment]
How did you get it to work?

**Comment by janelmer** [comment]
Same error here.

Error occurs when opening the browser at the given port. 
Gulp started the styleguide server and Msg `Styleguide server listening on port 88XX` is displayed.

**Comment by kestas-devbridge** [comment]
@shelune, @janelmer looks like you navigated to wrong page, are you opening `your-project-url/styleguide` url?

**Comment by janelmer** [comment]
yes i open that url in the browser and then i get the error in the console:

```
Styleguide server listening on port 8800
SyntaxError: Unexpected token { in JSON at position 49
    at Object.parse (native)
    at /Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/routes/snippets.js:35:23
    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at /Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:321:12)
    at next (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (/Applications/MAMP/htdocs/bedrock-dev/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:166:3)
```

**Comment by kestas-devbridge** [comment]
@janelmer could you post here your `styleguide/db/categories.txt` source?

**Comment by janelmer** [comment]
@kestas-devbridge thanks for that, there was an error in the `categories.txt` file. Set that back to default:

```
[
  {
    "name": "Undefined",
    "id": 0
  }
]
```
I now have the "New Snippet" button and so on in the browser view, but i got an resource error:

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/styleguide/db/categories.txt`

So this is missing one directory: http://localhost/<--my directory-->/styleguide/db/categories.txt

**Comment by gediminas-s** [comment]
Looks like this related to project setup and not tool itself. 
I'm closing this issue, feel free to reopen if needed.
