### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by fridzema** [devbridge/Styleguide#187]
Hello Devbridge,

I cant get your tool running at my app :(
I think because i run my app on a custom .dev domain.

I have set the correct path in the setting: `["resources/assets/sass/base/_variables.scss"]`

When i try to reach localhost:8889 the response i get is:
`
Error: Not Found
   at /Users/**/workspace/***/node_modules/devbridge-styleguide/app.js:36:13
   at Layer.handle [as handle_request] (/Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:302:13)
   at /Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:261:10)
   at /Users/**/workspace/***/node_modules/devbridge-styleguide/app.js:27:3
   at Layer.handle [as handle_request] (/Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:302:13)
   at /Users/**/workspace/***/node_modules/devbridge-styleguide/node_modules/express/lib/router/index.js:270:7
`

My current project i am working on is laravel project with laravel elixir (https://laravel.com/docs/5.2/elixir)
For the BrowserSync function i needed to set a proxy to get this working:
`
    mix.browserSync({
        proxy: 'project.app'
    });
`

I think i need some sort of same approach for this to get it working?

I hope you guys can help me out :)

**Comment by VaclovasV** [comment]
@fridzema 
maybe this will help, from documentation:
![image](https://cloud.githubusercontent.com/assets/3501072/16727953/57376d18-476c-11e6-80d2-c0e1633677fe.png)

**Comment by fridzema** [comment]
@VaclovasV
Thanks! 
This made me think to start the styleguide server on my vagrant machine.
Solved my question, though i think that a proxy option is a nice feature for this package!
