### ISSUE TITLE
Another issue about setup

### ISSUE THREAD

**Issue by pndparade** [devbridge/Styleguide#195]
Hello! Sorry if I repeat some issues, but I can't understand what I'm doing wrong.
I have a gulp project and want to run styleguide. I did 3 steps from your instruction and the last one was "styleguide initialize". My gulpfile.js:
```
"use strict";

var gulp = require('gulp'),
	watch = require('gulp-watch'),
	sass = require('gulp-sass'),
	prefixer = require('gulp-autoprefixer'),
	rigger = require('gulp-rigger'), 
	csscomb = require('gulp-csscomb'),
	plumber = require('gulp-plumber'),  
	rimraf = require('rimraf'), 
	browserSync = require("browser-sync"),
	reload = browserSync.reload;

//paths
var path = {
	build: {  
		html: 'public/',
		js: 'public/js/',
		style: 'public/css/',
		img: 'public/images/',
		fonts: 'public/fonts/'
	},
	src: {  
		html:'src/*.html', 
		js: 'src/js/**/*.js',
		style: 'src/style/style.scss',
		img: 'src/images/**/*.*',
		sprite: 'src/sprite/*.png',
		fonts: 'src/fonts/**/*.*'
	},
	watch: {   
		html: 'src/**/*.html', 
		js: 'src/js/**/*.js',
		style: 'src/style/**/*.*',
		img: 'src/images/**/*.*',
		fonts: 'src/fonts/**/*.*'
	},
	clean: 'public'
}

// server config
var config = {
	server: {
		baseDir: 'public/'
	},
	tunnel: false,
	host: 'localhost',
	port: 8080,
	logPrefix: "frontend_dev"
};

//clean
gulp.task('clean', function (cb) {
	rimraf(path.clean, cb);
});

//tasks
gulp.task('html', function () {
	gulp.src(path.src.html)
		.pipe(plumber())
		.pipe(rigger()) 
		.pipe(gulp.dest(path.build.html)) 
		.pipe(reload({stream: true})); 
});
gulp.task('style', function () {
	gulp.src(path.src.style) 
		.pipe(plumber())
        .pipe(sass().on('error', sass.logError)) 
        .pipe(prefixer({ browsers: ['> 1%'] })) 
        .pipe(gulp.dest(path.build.style)) 
        .pipe(reload({stream: true}));      
});
gulp.task('js', function () {
	gulp.src(path.src.js) 
	.pipe(plumber())
	.pipe(rigger()) 
	.pipe(gulp.dest(path.build.js)) 
	.pipe(reload({stream: true}));
});
gulp.task('image', function () {
	return gulp.src(path.src.img) 
	.pipe(plumber())
	.pipe(gulp.dest(path.build.img)) 
	.pipe(reload({stream: true}));
});
gulp.task('fonts', function() {
	gulp.src(path.src.fonts)
	.pipe(plumber())
	.pipe(gulp.dest(path.build.fonts));
});

// common task build
gulp.task('build', [
	'html',
	'js',
	'style',
	'fonts',
	'image'
	]);

//watch
gulp.task('watch', function(){
	watch([path.watch.html], function(event, cb) {
		gulp.start('html');
	});
	watch([path.watch.style], function(event, cb) {
		gulp.start('style');
	});
	watch([path.watch.js], function(event, cb) {
		gulp.start('js');
	});
	watch([path.watch.img], function(event, cb) {
		gulp.start('image');
	});
	watch([path.watch.fonts], function(event, cb) {
		gulp.start('fonts');
	});
});

//server
gulp.task('webserver', function () {
	browserSync(config);
	console.log('Сервер работает по адресу http://localhost:8080');
});

//styleguide
var styleguide = require('devbridge-styleguide');

gulp.task('start-styleguide', function () {
  styleguide.startServer();
});

// default
gulp.task('default', ['build', 'webserver', 'start-styleguide', 'watch']);
```

So, I wrote start-styleguide task and added it in default task. 

When I open localhost:8889 I see this mess:
```
Error: Not Found
   at C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\app.js:36:13
   at Layer.handle [as handle_request] (C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\layer.js:82:5)
   at trim_prefix (C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:302:13)
   at C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:261:10)
   at C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\app.js:27:3
   at Layer.handle [as handle_request] (C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\layer.js:82:5)
   at trim_prefix (C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:302:13)
   at C:\Users\pndparade\Desktop\test\node_modules\devbridge-styleguide\node_modules\express\lib\router\index.js:270:7
```
When I open localhost:8080/styleguide/index.html I see this:
`Cannot GET /styleguide/index.html`

Files in styleguide folder have not been changed after initialization.

UPD:
Structure of project:
```
- node_modules
- public
---- css
---- images
---- fonts
---- js
---- index.html
- src
---- fonts
---- html
---- images
---- js
---- style
---- index.html
- styleguide
- gulpfile.js
- package.json
```

**Comment by miezis** [comment]
Was your web server (8080 port) configured to expose styleguide as static resource?

**Comment by pndparade** [comment]
I use 'browserSync' for running server. This is options:
```
var config = {
    server: {
        baseDir: 'public/'
    },
    tunnel: false,
    host: 'localhost',
    port: 8080,
    logPrefix: "frontend_dev"
};
```
Should I add something more?

**Comment by pndparade** [comment]
Oh, I think I see what's wrong... Styleguide folder should be in the same directory as project files.

**Comment by nathan5x** [comment]
Am getting the same issue. My styleguide folder is inside the project folder. Wondering whats the issue? I tried clearing the cache. It didn't work. Any tips?
